### ISSUE TITLE
Missing and misplaced track(s)

### ISSUE THREAD

**Issue by kokarn** [gillesdemey/Cumulus#9] opened 2015-08-19 09:35 UTC
Hello!

I'm back from vacation and with it comes more issue reports (sorry :P)

I just noticed some tracks are missing from my feed and some seem "misplaced" or just appear in another order.
I've included screenshots below for the relevant part of my feed.

The issue persists even if I restart Cumulus and I updated to the latest available version (0.3.5) yesterday.

Anything i can help to debug this?

##### Missing: 3lau Haus #37 (Number 13 in my list on soundcloud.com)
![Cumulus](https://i.imgur.com/DZx7mZ3.png)
![Soundcloud.com](https://i.imgur.com/wyS5101.png)

##### Missing: Premiere: ATTLAS 'Rasor' (Number 30 in my list on soundcloud.com)
![Cumulus](https://i.imgur.com/dNX847X.png)
![Soundcloud.com](https://i.imgur.com/BgIEvHP.png)

##### Misplaced: Dillon Francis & Skrillex - Bun Up The Dance
![Cumulus](https://i.imgur.com/94SYMLO.png)
![Soundcloud.com](https://i.imgur.com/NXxgBjl.png)

**Comment by Bitbored** [comment] 2015-08-20 12:04
As far as I can see, the [3LAU HAUS #37 (Back To School)](https://soundcloud.com/3lau/3lau-haus-37-back-to-school?in=3lau/sets/3lau-haus) track is new, but is part of an [album that is more than 3 years old](https://soundcloud.com/3lau/sets/3lau-haus). Cumulus displays full albums in the feed view, and Soundcloud does not update the release date of the albums if a new track is added.

**Comment by kokarn** [comment] 2015-08-20 12:42
That makes sense.

Any thoughts on the other 2 tracks? 
The last one is probably the same thing but the second one, Premiere: ATTLAS 'Rasor', doesn't make any sense at all to me.

**Comment by Bitbored** [comment] 2015-08-20 14:20
I think the missing "Premiere: Premiere: ATTLAS 'Rasor'" track is caused by a re-post: it was re-posted by mau5trap records on 05/08, while the original was posted on 29/07. In your last image you can see Cumulus has actually placed the song in your feed, however on the location it was originally posted.

Personally I think the behavior of Cumulus makes more sense than the behavior of Soundcloud's web interface. However I understand Soundcloud's reasoning to place reposted tracks on top in order to allow old tracks to be "dug up".

Cumulus simply orders tracks based on the track id. I suppose this id is generated when the track was first created, so essentially the tracks are ordered by creation date. We could sort tracks based on the [`created_at` property of the origin object](https://developers.soundcloud.com/docs/api/reference#activities). I think this would result in the same ordering as the Soundcloud website.

**Comment by kokarn** [comment] 2015-08-20 14:37
That makes sense, and might explain another issue that's not related to Cumulus. 
I have one track posted by Hirshee,
```The Police - Message In A Bottle (Hirshee Remix) [FREE DOWNLOAD]``` that keeps reappearing. It's re-posted by Big-Fish Recordings and then maybe that re-post is "re-created" and that timestamp is used. Same both in Cumulus and on Soundcloud.com

How about an option to select sorting? 
Is that hard to implement?
Probably needs a option screen anyways, to remove accounts and whatnot.

**Comment by gillesdemey** [comment] 2015-08-20 17:22
Sadly SoundCloud's public API does not accurately reflect the SoundCloud homepage, which uses their newer — but private — API.

There's not much we can do on our end without making the experience all weird for the user.

When we get around to implementing pagination, we wouldn't want any items to shift around because we're sorting the items every time.

I'm going to set this to 'wontfix' for now, but I'll revisit this issue when SoundCloud gets around to releasing their newer API.

**Closed by gillesdemey** 2015-08-20 17:22 UTC

**Comment by kokarn** [comment] 2015-08-21 05:36
Ah, that sucks! 
Totally understandable that you won't fix this. Not that big of an issue anyways :)

Cheers for the great communication <3
