### ISSUE TITLE
All tracks are unplayable 

### ISSUE THREAD

**Issue by romainsassareu** [gillesdemey/Cumulus#103] opened 2017-07-08 11:58 UTC
Hello, 

All tracks are unplayable. 

<img width="325" alt="skitch" src="https://user-images.githubusercontent.com/10031826/27985120-b092ed26-63ed-11e7-957c-bcb0752a931d.png">

Setup: Cumulus v0.10.1 x macOS Sierra Version 10.12.5

Any idea? 

Thanks! 

Romain

**Comment by MichielDeMey** [comment] 2017-07-08 14:04
Yup, duplicate of https://github.com/gillesdemey/Cumulus/issues/89. :)

**Closed by MichielDeMey** 2017-07-08 14:04 UTC
