### ISSUE TITLE
Skips every song upon playing. 

### ISSUE THREAD

**Issue by neroh29** [gillesdemey/Cumulus#94] opened 2017-05-16 08:37 UTC
Pretty much as soon as i start a new playlist, favorites it just skips all tracks and crosses them out and never plays anything. Tried full uninstall and still happens.

**Comment by MichielDeMey** [comment] 2017-05-16 08:38
Duplicate of https://github.com/gillesdemey/Cumulus/issues/89

**Closed by MichielDeMey** 2017-05-16 08:38 UTC
