### ISSUE TITLE
Fresh install - trying to sign in via Google

### ISSUE THREAD

**Issue by walshie4** [gillesdemey/Cumulus#67] opened 2016-09-01 16:31 UTC
When doing so I am prompted with the following error and then Cumulus goes unresponsive.

![image](https://cloud.githubusercontent.com/assets/945703/18175655/e928c93c-7026-11e6-8bbe-8f464cbce2f0.png)

**Comment by MichielDeMey** [comment] 2016-09-01 16:39
Duplicate of https://github.com/gillesdemey/Cumulus/issues/34

**Closed by MichielDeMey** 2016-09-01 16:39 UTC
