### ISSUE TITLE
ubuntu/other linux distros

### ISSUE THREAD

**Issue by sergiuprt** [gillesdemey/Cumulus#64] opened 2016-06-23 12:13 UTC
hey guys! can you port Cumulus on linux? it is a nice soundcloud client, beautiful one, is there a possibility to port it?

**Comment by gillesdemey** [comment] 2016-06-23 12:20
Not impossible, but your mileage may vary greatly depending on what distro you're using.

The menubar library that we're using (https://github.com/maxogden/menubar) has been tested on xfce4, but there have been various bug reports on other desktop environments (most notably Ubuntu with Unity).

I'm willing to accept patches that enhance the experience on Linux — and if someone can confirm that it works on their distro I'll create binaries for it with any new releases.

**Comment by sergiuprt** [comment] 2016-06-23 12:27
i'm on ubuntu 16.04, with unity, and many others users..
i can't code it, but i'm ready to test it whenever is needed and to find others testers.. also to contribute on sharing..

**Comment by seppestas** [comment] 2016-07-28 12:47
This app does not work on Ubuntu or other distros using [libappindicator](https://launchpad.net/libappindicator) since [the new API explicitly prevents this type of app](https://wiki.ubuntu.com/DesktopExperienceTeam/ApplicationIndicators).

Ubuntu protects you from the inconsistency that comes with apps that try to be fancy, instead offering you a beautifully consistent gray smudge.

I'm trying to work around the limitations set by libappindicator, but this has to be done in the Chromium sources, so don't expect it to be fixed soon.

IMO this issue can be closed, since it is definitely not in the scope of this project.

**Comment by seppestas** [comment] 2016-07-29 13:11
Closing since this issue is caused by Linux desktop environments, not Cumulus itself.

**Closed by seppestas** 2016-07-29 13:11 UTC
