### ISSUE TITLE
Unable to play tracks

### ISSUE THREAD

**Issue by lukacosicnz** [gillesdemey/Cumulus#99] opened 2017-06-24 07:28 UTC
I just installed v0.10.1 as a clean install from the dmg, logged into my soundcloud account, and no song will play, they just skip. I tried logging out, quitting, didn't help.

Here's a screen recording of it:
[bug.mp4.zip](https://github.com/gillesdemey/Cumulus/files/1099485/bug.mp4.zip)

**Comment by MichielDeMey** [comment] 2017-06-24 09:35
Sounds like a duplicate of https://github.com/gillesdemey/Cumulus/issues/89. Best to follow the progress in that ticket.

**Closed by MichielDeMey** 2017-06-24 09:35 UTC
