### ISSUE TITLE
Cannot play any songs

### ISSUE THREAD

**Issue by aleclarson** [gillesdemey/Cumulus#106] opened 2017-08-11 18:40 UTC
When I hit the play button, it automatically skips to the next song, and then the next song, until no songs are left. I've attached a video demonstrating the issue.

MacOS v10.12.3
Cumulus v0.10.1

<a href="https://drive.google.com/file/d/0B04xVppKr0fARDlqQjZZQ0thd0E/view">
<img src="https://lh3.googleusercontent.com/xeZ0t6MkNnqV4NvSGZNII5gECDLiXJR_qGFE05bY2rf1XOztgUiSvTsSefIN-YYoNpOsBrhzXriuhXg=w1920-h1080-n-k-rw"/>
</a>

**Comment by Hum4n01d** [comment] 2017-08-12 04:14
Duplicate of #89

**Comment by MichielDeMey** [comment] 2017-08-12 09:18
Yep, unfortunately it's a duplicate of #89.
We still haven't heard from Soundcloud for a solution.

**Closed by MichielDeMey** 2017-08-12 09:18 UTC
