### ISSUE TITLE
The app doesn't play any tracks on first start

### ISSUE THREAD

**Issue by avalan4e57** [gillesdemey/Cumulus#105] opened 2017-07-29 10:11 UTC
On my first app start I've tried to play something from my likes or playlists. Shows up in player but doesn't play. In playlist this track becomes ~~strikethrough~~. Then all tracks in playlist pass through player and stop on the last track while all of the tracks in list become ~~strikethrough~~ also. Looks very strange to me. Maybe there's something needed to be installed first? Or if it's a bug please help me find out and fix it.

**Comment by MichielDeMey** [comment] 2017-07-29 10:17
Hi, seems like a duplicate of https://github.com/gillesdemey/Cumulus/issues/89.
Can you verify?

**Closed by MichielDeMey** 2017-07-29 10:17 UTC

**Comment by avalan4e57** [comment] 2017-07-29 10:20
Hi, yes I think that's the same problem. Sorry for that but I think it's better to report a bug and make a duplicate then not to report and get unexpected problems in future.
