### ISSUE TITLE
Needed search feature within app

### ISSUE THREAD

**Issue by bbblueboy** [gillesdemey/Cumulus#84] opened 2017-01-29 19:51 UTC
There is no search option and I think that would be an awesome feature to add!

**Comment by gillesdemey** [comment] 2017-01-29 20:02
Duplicate of #1

TL;DR I'm not willing to add this feature but am willing to thoughtfuly review any PR if someone decides to take a stab at it.

**Closed by gillesdemey** 2017-01-29 20:02 UTC
