### ISSUE TITLE
Songs cannot be played

### ISSUE THREAD

**Issue by zakiaziz** [gillesdemey/Cumulus#108] opened 2017-10-26 18:12 UTC
I've signed in via google and when I hit a song to play it attempts to play but doesn't. A strikethrough is applied to the name of the song then the next song is tried. The same problem occurs throughout the playlist.
![screen shot 2017-10-26 at 2 10 11 pm](https://user-images.githubusercontent.com/940281/32069613-abc3a400-ba57-11e7-9aa6-ad7d67dfdf6b.png)

**Comment by MichielDeMey** [comment] 2017-10-26 21:19
Hi, looks like a duplicate of https://github.com/gillesdemey/Cumulus/issues/89.

Unfortunately, nothing we can do about that at this moment. 🙂

**Closed by MichielDeMey** 2017-10-26 21:19 UTC
