### ISSUE TITLE
Playback not working

### ISSUE THREAD

**Issue by ivanlemeshev** [gillesdemey/Cumulus#91] opened 2017-04-08 15:12 UTC
I can't listen to anything. It is not plays any track. What's wrong?

![image](https://cloud.githubusercontent.com/assets/2150567/24830025/69537ad8-1c9f-11e7-80b8-e85e77fe2672.png)

macOS Sierra 10.12.4

**Comment by MichielDeMey** [comment] 2017-04-08 15:13
Possible duplicate of https://github.com/gillesdemey/Cumulus/issues/89

**Closed** 2017-04-08 15:13 UTC
